variables:
  FORGEJO_VERSION: 6.2.2
  WOODPECKER_VERSION: 3.4.0
  GO_VERSION: 1.24.1
  IMAGE_NAME: ci-runner
  GIT_SUBMODULE_STRATEGY: recursive
#  BUILDX_VERSION: v0.21.1
#  DOCKER_CREDENTIAL_HELPER_VERSION: v0.9.1
#  CI_REGISTRY_USER: xxx
#  CI_REGISTRY_PASSWORD: xxx
  CI_REGISTRY_IMAGE: ravermeister/${IMAGE_NAME}
  GPG_USER: ci-runner
  GPG_MAIL: ci-runner@example.net
  DOCKER_AUTH_CONFIG: |
    {
      "credsStore": "pass"
    }

include:
  - local: .gitlab/.gitlab-ci.tpl.yml

stages:
  - build
  - release

create_arm64:
  stage: build
  extends:
    - .arm64
    - .create

create_amd64:
  stage: build
  extends:
    - .amd64
    - .create

manifest:
  stage: release
  extends:
    - .amd64
  needs:
    - create_arm64
    - create_amd64
  script:
    - echo "creating tags"
    # creating initial 'latest' and 'version' tag with amd64 image
    - docker buildx imagetools create --tag "${CI_REGISTRY_IMAGE}:latest" "${CI_REGISTRY_IMAGE}:amd64"
    - docker buildx imagetools create --tag "${CI_REGISTRY_IMAGE}:${FORGEJO_VERSION}" "${CI_REGISTRY_IMAGE}:amd64"
    - docker buildx imagetools create --tag "${CI_REGISTRY_IMAGE}:${WOODPECKER_VERSION}" "${CI_REGISTRY_IMAGE}:amd64"
    # append arm64 image to 'latest' and 'version' tag
    - docker buildx imagetools create --append --tag "${CI_REGISTRY_IMAGE}:latest" "${CI_REGISTRY_IMAGE}:arm64"
    - docker buildx imagetools create --append --tag "${CI_REGISTRY_IMAGE}:${FORGEJO_VERSION}" "${CI_REGISTRY_IMAGE}:arm64"
    - docker buildx imagetools create --append --tag "${CI_REGISTRY_IMAGE}:${WOODPECKER_VERSION}" "${CI_REGISTRY_IMAGE}:arm64"
