variables:
  FORGEJO_RUNNER_VERSION: 6.2.2
  GO_VERSION: 1.24.1
  IMAGE_NAME: forgejo-runner
  GIT_SUBMODULE_STRATEGY: recursive
#  BUILDX_VERSION: v0.21.1
#  DOCKER_CREDENTIAL_HELPER_VERSION: v0.9.1
#  
#  CI_REGISTRY_PASSWORD: xxx
  CI_REGISTRY_IMAGE: ravermeister/${IMAGE_NAME}
  GPG_USER: forgejo
  GPG_MAIL: forgejo@example.net
  DOCKER_AUTH_CONFIG: '
    {
      "credsStore": "pass"
    }
  '

include:
  - local: .gitlab/.gitlab-ci.tpl.yml
  - local: .gitlab/.gitlab-ci.arm64.yml
  - local: .gitlab/.gitlab-ci.amd64.yml

stages:
  - create
  - release
