variables:
#  CI_REGISTRY_USER: xxx
#  CI_REGISTRY_PASSWORD: xxx
  DOCKER_BUILD_IMAGE_NAME: ci-runner
  CI_REGISTRY_BUILD_IMAGE_NAME: ravermeister/${DOCKER_BUILD_IMAGE_NAME}
  GIT_SUBMODULE_STRATEGY: recursive  
  GPG_USER: ci-runner
  GPG_MAIL: ci-runner@example.net
  DOCKER_AUTH_CONFIG: |
    {
      "credsStore": "pass"
    }

include:
  - local: .gitlab/.gitlab-ci.tpl.yml

stages:
  - build
  - release

create_arm64:
  stage: build
  extends:
    - .arm64
    - .create

create_amd64:
  stage: build
  extends:
    - .amd64
    - .create

manifest:
  stage: release
  extends:
    - .amd64
  needs:
    - create_arm64
    - create_amd64
  variables:
    DOCKER_TAGS: |
      latest 
      forgejo-runner
      forgejo-runner-${FORGEJO_VERSION}
      gitlab-runner
      gitlab-runner-${GITLAB_VERSION}
      woodpecker-agent
      woodpecker-agent-${WOODPECKER_VERSION}
  script:
    - |
      for tag in $(printf "$DOCKER_TAGS" | xargs); do
        printf "creating tag ${CI_REGISTRY_IMAGE}:${tag}"
        docker buildx imagetools create --tag "${CI_REGISTRY_IMAGE}:${tag}" "${CI_REGISTRY_IMAGE}:amd64"  
        docker buildx imagetools create --append --tag "${CI_REGISTRY_IMAGE}:${tag}" "${CI_REGISTRY_IMAGE}:arm64"
      done
