# amd64 env template
.amd64:
  extends: .dind
  variables:
    DOCKER_ENV_FILE: .env/amd64.env
  tags: []

# arm64 env template
.arm64:
  extends: .dind
  variables:
    DOCKER_ENV_FILE: .env/arm64.env
  tags:
    - arm64
    - docker

# create image template
.create:
  before_script:
    - printf "Loading environment variables from ${DOCKER_ENV_FILE} file"    
    - export $(grep -v '^[[:space:]]*#' ${DOCKER_ENV_FILE} | xargs)    
    - |
      printf "building Versions:\n"
      printf "Forgejo Runner:\t%s\n" "$FORGEJO_VERSION"
      printf "Woodpecker Agent:\t%s\n" "$WOODPECKER_VERSION"
      printf "Gitlab Runner:\t%s\n" "$GITLAB_VERSION"    
      printf "Go Version:\t%s\n" "$GO_VERSION"

      printf "building environment:\n"
      printf "BASE_IMAGE:\t%s\n" "$BASE_IMAGE"
      printf "BUILDX_ARCHITECTURE:\t%s\n" "$BUILDX_ARCHITECTURE"
      printf "DOCKER_CREDENTIAL_HELPER_ARCHITECTURE:\t%s\n" "$DOCKER_CREDENTIAL_HELPER_ARCHITECTURE"
      printf "FORGEJO_ARCH:\t%s\n" "$FORGEJO_ARCH"
      printf "WOODPECKER_ARCH:\t%s\n" "$WOODPECKER_ARCH"
      printf "GITLAB_ARCH:\t%s\n" "$GITLAB_ARCH"
      printf "GO_ARCH:\t%s\n" "$GO_ARCH"
    
  script:    
    - >
      docker buildx build --no-cache --force-rm --compress --load \      
        --platform "$DOCKER_TARGET_PLATFORM" \                
        --build-arg "DOCKER_BASE_IMAGE=$DOCKER_BASE_IMAGE" \
        --build-arg "FORGEJO_VERSION=$FORGEJO_VERSION" \
        --build-arg "WOODPECKER_VERSION=$WOODPECKER_VERSION" \
        --build-arg "GO_VERSION=$GO_VERSION" \
        --build-arg "BASE_IMAGE=$DOCKER_BASE_IMAGE" \
        --build-arg "FORGEJO_ARCH=$FORGEJO_ARCH" \
        --build-arg "WOODPECKER_ARCH=$WOODPECKER_ARCH" \
        --build-arg "GITLAB_ARCH=$GITLAB_ARCH" \
        --build-arg "GO_ARCH=$GO_ARCH" \
        --target "$DOCKER_BUILD_TARGET" \
        -t "${IMAGE_NAME}" \
        -t "${CI_REGISTRY_IMAGE}:${DOCKER_TARGET_IMAGE_TAG}" \
        .
    - docker push "${CI_REGISTRY_IMAGE}:${DOCKER_TARGET_IMAGE_TAG}"

# docker in docker template
.dind:
  image: docker
  services:
    - name: docker:dind
      command: ["--experimental"]
  before_script:
    - apk add --no-cache make bash curl libsecret pass gpg-agent openssh-client
    - .gitlab/docker-credential-init.sh "${GPG_USER}" "${GPG_MAIL}"
    - mkdir -p ~/.docker/cli-plugins
    - curl -sSLo ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/$BUILDX_VERSION/buildx-$BUILDX_VERSION.$BUILDX_ARCHITECTURE
    - chmod +x ~/.docker/cli-plugins/docker-buildx
    - mkdir -p /usr/local/bin
    - curl -sSLo /usr/local/bin/docker-credential-pass https://github.com/docker/docker-credential-helpers/releases/download/$DOCKER_CREDENTIAL_HELPER_VERSION/docker-credential-pass-$DOCKER_CREDENTIAL_HELPER_VERSION.$DOCKER_CREDENTIAL_HELPER_ARCHITECTURE
    - chmod +x /usr/local/bin/docker-credential-pass
    - docker context create tls-environment >/dev/null
    - docker buildx create --use tls-environment >/dev/null
    - echo "${DOCKER_AUTH_CONFIG}" > ~/.docker/config.json
    - echo "${CI_REGISTRY_PASSWORD}" | awk '{print $0}' | docker login --username "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"
  after_script:
    - docker logout
