create_amd64:
  stage: create
  extends:
    - .amd64
  script:
    - echo "build Forgejo Runner Version $FORGEJO_RUNNER_VERSION"
    - >
      docker buildx build --no-cache --force-rm --compress --load \
        --platform "linux/amd64" \
        --build-arg FORGEJO_VERSION=$FORGEJO_RUNNER_VERSION \
        --build-arg GO_VERSION=$GO_VERSION \
        --target forgejo-runner-amd64 \
        -t "${IMAGE_NAME}" \
        -t "${CI_REGISTRY_IMAGE}:amd64" \
        .
    - docker push "${CI_REGISTRY_IMAGE}:amd64"
