#!/bin/bash

start_container() {
	case "$CI_RUNNER" in
		"woodpecker")
			woodpecker-agent
		;;
		"gitlab")
			printf "gitlab start not yet implemented" >&2
			exit 1
		;;
		*)
			forgejo-runner -c /etc/forgejo.yml daemon
		;;
	esac
}

usage() {
	BASE_NAME="$(basename "$0")"
	printf "%s\t%s\t%s\n" "${BASE_NAME}" "run" "starts the [forgejo-runner|woodpecker-agent|gitlab-runner]"
}

###########

case $1 in
	run)
		start_container
	;;
	*)
		usage
	;;
esac
