#!/bin/bash

update_system() {
	apt -yq update
  apt -yq dist-upgrade
}
install_docker_cli() {
		# Add Docker's official GPG key:
    apt -yq update
    apt -yq install ca-certificates curl
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc

    # Add the repository to Apt sources:
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
      tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update
}

install_node() {
	apt -yq install nodejs
}


init_container() {
	update_system
	install_docker_cli
	install_node
}

start_container() {
	/usr/local/share/forgejo/forgejo-runner daemon
}
