#!/bin/bash

update_system() {
	apt -yq update
    apt -yq dist-upgrade
}

install_docker_cli() {
	# Add Docker's official GPG key:
    apt -yq update
    apt -yq install ca-certificates curl
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc

    # Add the repository to Apt sources:
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
      tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt -yq update
	apt -yq install docker-ce-cli
}

install_node() {
	apt -yq install nodejs
}

install_tools() {
	tar -C /usr/local -xzf /tmp/tools/go.tar.gz
	rm -rf /tmp/tools
}

init_container() {
	update_system
	install_docker_cli
	install_node
	install_tools
}

start_container() {
	/usr/local/share/forgejo/forgejo-runner daemon
}

usage() {
	BASE_NAME="$(basename "$0")"
	printf "%s\t%s\t%s\n" "${BASE_NAME}" "setup" "installs all necessary packages"
	printf "%s\t%s\t%s\n" "${BASE_NAME}" "run" "starts the forgejo-runner"
}

###########

case $1 in
	setup)
		init_container
	;;
	run)
		start_container
	;;
	*)
		usage
	;;
esac
